//go:build !ignore_autogenerated

/*
Copyright 2025 wuyong7240.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LSTMPredictApp) DeepCopyInto(out *LSTMPredictApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LSTMPredictApp.
func (in *LSTMPredictApp) DeepCopy() *LSTMPredictApp {
	if in == nil {
		return nil
	}
	out := new(LSTMPredictApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LSTMPredictApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LSTMPredictAppList) DeepCopyInto(out *LSTMPredictAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LSTMPredictApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LSTMPredictAppList.
func (in *LSTMPredictAppList) DeepCopy() *LSTMPredictAppList {
	if in == nil {
		return nil
	}
	out := new(LSTMPredictAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LSTMPredictAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LSTMPredictAppSpec) DeepCopyInto(out *LSTMPredictAppSpec) {
	*out = *in
	if in.BackendAppReplicas != nil {
		in, out := &in.BackendAppReplicas, &out.BackendAppReplicas
		*out = new(int32)
		**out = **in
	}
	in.ResourcesLimit.DeepCopyInto(&out.ResourcesLimit)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LSTMPredictAppSpec.
func (in *LSTMPredictAppSpec) DeepCopy() *LSTMPredictAppSpec {
	if in == nil {
		return nil
	}
	out := new(LSTMPredictAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LSTMPredictAppStatus) DeepCopyInto(out *LSTMPredictAppStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LSTMPredictAppStatus.
func (in *LSTMPredictAppStatus) DeepCopy() *LSTMPredictAppStatus {
	if in == nil {
		return nil
	}
	out := new(LSTMPredictAppStatus)
	in.DeepCopyInto(out)
	return out
}
